<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>About</title>
</head>
<body>
<h1>Everything about the film</h1>

<?php
if (!empty($_SESSION['user_login']))
    echo '
<div class="container">
    <div class="row align-items-end justify-content-end">
        <div class="col-4">
            <p class="alert alert-primary" role="alert"> Welcome, '. $_SESSION["user_login"].'</p>
            <a class="btn btn-primary" href="/logout" role="button">Logout</a>
            <a class="btn btn-primary" href="/" role="button">Main</a>
            </div>    
    </div> 
</div>
';
?>

<?php
if(!empty($films)){
echo'
<div class="container">
    <div class="row justify-content-start">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">'.$films[0]->title.'</h5>
                <h6 class="card-subtitle mb-2 text-muted">Year of production: '.$films[0]->year.'</h6>
                <h6 class="card-subtitle mb-2 text-muted">Available format: '.$films[0]->format.'</h6>
                <h6 class="card-subtitle mb-2 text-muted">Actors:</h6>
                <ul class="list-group list-group-flush">';
    foreach($films as $film){
        echo '<li class="list-group-item">'.$film->full_name.'</li>';
    };
echo '
                
                </ul>
            </div>
        </div>';

}
?>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
</body>
</html>