<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Add new film</title>
</head>
<body>
<h1>Add new film</h1>
<?php
if (!empty($_SESSION['user_login']))
    echo '
<div class="container">
    <div class="row align-items-end justify-content-end">
        <div class="col-4">
            <p class="alert alert-primary" role="alert"> Welcome, '. $_SESSION["user_login"].'</p>
            <a class="btn btn-primary" href="/logout" role="button">Logout</a>
            <a class="btn btn-primary" href="/" role="button">Main</a>
            </div>    
    </div> 
</div>
';
?>

<?php

if (!empty($_SESSION["alert"])){
    echo ' <div class="alert alert-warning" role="alert">
                    ' .$_SESSION["alert"] . '
                </div>';
}
unset($_SESSION["alert"]);
?>
<div class="container-sm">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <form action="/addfilm" method="post">
                <div class="mb-2">
                    <label for="title" class="form-label">Title</label>
                    <input required type="text" class="form-control" id="title" name="Title" placeholder="Input film title">
                </div>
                <div class="mb-2">
                    <label for="year" class="form-label">Year</label>
                    <input required type="number" max="9999" maxlength="4" class="form-control" id="year" name="ReleaseYear" placeholder="Input year of production">
                </div>

                <div class="mb-2">
                    <label for="format" class="form-label">Choose Film Format</label>
                    <select  class="form-select" id="format" name="Format"  aria-label="Disabled select example" required>
                        <option value=""selected disabled>Open this select menu</option>
                        <option value="VHS">VHS</option>
                        <option value="DVD">DVD</option>
                        <option value="Blu-ray">Blu-ray</option>
                    </select>
                </div>
                <div class="mb-2">
                    <label for="actors" class="form-label">Actors</label>
                    <textarea required class="form-control" id="Stars" name="Stars" rows="3" placeholder="Will Sith, Bruce Willis..."></textarea>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>



<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
</body>
</html>