<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>
<h1>Hello, world!</h1>

<?php
if (!empty($_SESSION['user_login']))
    echo '
<div class="container">
    <div class="row align-items-end justify-content-end">
        <div class="col-4">
            <p class="alert alert-primary" role="alert"> Welcome, '. $_SESSION["user_login"].'</p>
            <a class="btn btn-primary" href="/logout" role="button">Logout</a>
            <a class="btn btn-primary" href="/" role="button">Main</a>
            </div>    
    </div> 
</div>
';
?>


<div class="container">
    <div class="row">
        <h2>
            Films
        </h2>
    <div class="row justify-content-center">
        <div class="col-4">
            <a class="btn btn-primary" href="/addfilm" role="button">Add film</a>
            <a class="btn btn-primary" href="/upload" role="button">Upload file</a>
        </div>
        <div class="col-4">
            <form method="post" action="/searchbyactor">
                <label for="search_by_actor" class="form-label">Search by actor</label>
                <input id="search_by_actor" name="actor" type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
            <button type="submit" class="btn btn-outline-primary">search</button>
            </form>
        </div>
        <div class="col-4">
            <form method="post" action="/searchbyname">
                <label for="search_by_name" class="form-label">Search by name</label>
                <input id="search_by_name" name="name" type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
            <button type="submit" class="btn btn-outline-primary">search</button>
            </form>
        </div>
    </div>
    </div>
</div>
<?php

if (!empty($_SESSION["alert"])){
    echo ' <div class="alert alert-warning" role="alert">
                    ' .$_SESSION["alert"] . '
                </div>';
}
unset($_SESSION["alert"]);
?>
<table class="table">
    <thead>
    <tr>
        <th scope="col">id</th>
        <th scope="col">Title</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <?php
    if (!empty($films)){
        foreach ($films as $film){
            echo '<tr>';
            echo'<th scope="row">'.$film->id.'</th>';
            echo'<td><a class="btn btn-link" href="/film?id='.$film->id.'" role="button">'.$film->title.'</a></td>';
            echo'<td> <a class="btn btn-primary" href="/filmdelete?id='.$film->id.'" role="button">Delete</a></td>';
            echo '</tr>';
        }
    }
    ?>


    </tbody>
</table>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
</body>
</html>